name=@extname@
description=The extension description can be customized by editing the extension.properties file.
author=achan1989, SomeoneIsWorking, blackerking
createdOn= 2026_04_10
version=@extversion@
